# -*- coding: utf-8 -*-
"""2025-12-31_RegressãoLinearSimples–PrevisãoVendasPublicidade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CgDoX-sQTwaDA3U7Qy9aNOg0iaBmGmow

# **Cenário proposto:**

A empresa Hsouza Soluções é uma startup que vende
software de análise de dados. Ela coletou dados sobre
os gastos mensais em publicidade (em milhares de
reais) e o número de licenças de software vendidas por
mês ao longo de um ano.
A empresa deseja entender a relação entre gastos com
publicidade e vendas de licenças para poder otimizar
seu orçamento de marketing.

**Objetivo**: Utilizando regressão linear, crie um modelo
que preveja o número de licenças vendidas com base
nos gastos com publicidade.
"""

#Importacoes de bibliotecas necessaruas para analise e vizualizacao de dados, alem de aprendizado de maquina

import matplotlib.pyplot as plt #Graficos
import numpy as np #Operacoes e manipulacoes de arrays
from sklearn.linear_model import LinearRegression #Criar o modelo de Regressao Linear
from sklearn.metrics import mean_squared_error, r2_score #Metricas de avaliacao do modelo

# Gastos mensais com publicidade (em milhares de dólares)
gastos_publicidade = [1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0]
# Número de licenças vendidas por mês
licenças_vendidas = [50, 55, 60, 68, 72, 80, 85, 88, 90, 95, 100, 105]

#Conversao das listas em arrays numpy, formato necessario para uso com scikit-learn, e ajuste para valores em reais.
X = np.array(gastos_publicidade).reshape(-1,1) * 1000 #Gatos com publicidad em real
y = np.array(licenças_vendidas) * 1000 #Licenças vendidas em real

#Criacao do modelo de regressao Linear ultilizando a biblioteca sckit-learn.
model = LinearRegression()
model.fit(X,y)

y_pred = model.predict(X) #Predicao dos valores de y com base nos valores de X
mse = mean_squared_error(y, y_pred) #Calculo do erro quadratico medio
r2 = r2_score(y, y_pred) #Calculo do coeficiente de determinacao

#Geracao e configuracao do grafico para vizulizar os dados e a linha de regressao
plt.figure(figsize=(10,6))
plt.scatter(X, y, color='blue', label='Dados reais')
plt.plot(X, y_pred, color='red', linewidth=2, label='Regressão Linear')

#Adicao de titlulos e rotulos aos eixos do grafico para melhor compreesao
plt.xlabel('Gastos com Publicidade (em milhoes de reais)')
plt.ylabel('Número de Licenças Vendidas (em milhoes de reais)')
plt.title('Regressão Linear de Licenças Vendidas x Gastos com Publicidade')
plt.legend()
plt.show()

#PREVISAO
#Uso do modelo treinado para prever o numero de licencas vendidas com um gasto de R$8.000 em publicidade
previsao = model.predict(np.array([[8000]]))

#Os resultados das metricas de avaliacao e a previsao sao apresentados.
mse, r2, previsao

